name: Snapshot Releases

# Only run on pushes to main:
# Replace with 'on: [push]' if you need to run tests on your PR
on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
        # Modules specify the oldest java version that they support:
        # even if we build with version 21, produced jars should be compatible with
        # JVMs running the version specified in each module's maven.compiler.target property
          java-version: '21'
          distribution: 'temurin'
          server-id: vzotov-snapshots
          server-username: MAVEN_REPO_USERNAME
          server-password: MAVEN_REPO_PASSWORD
      - name: Publish package
        env:
          MAVEN_REPO_USERNAME: ${{ secrets.MAVEN_REPO_USERNAME }}
          MAVEN_REPO_PASSWORD: ${{ secrets.MAVEN_REPO_PASSWORD }}
        # Notes:
        #  - tests already run in a separate action
        run: mvn -B -U --fail-at-end deploy -DskipTests
